<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateResourceDesignerFiles>true</GenerateResourceDesignerFiles>
    <CoreCompileDependsOn>PrepareResources;$(CompileDependsOn)</CoreCompileDependsOn>
  </PropertyGroup>


  <ItemGroup>
    <EmbeddedResource Update="Resources\ErrorMessages.resx">
      <Generator>MSBuild:Compile</Generator>
      <PublicClass>True</PublicClass>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <StronglyTypedLanguage>CSharp</StronglyTypedLanguage>
      <StronglyTypedNamespace>TcfOss.DatabaseManager.Core.Resources</StronglyTypedNamespace>
      <StronglyTypedClassName>ErrorMessages</StronglyTypedClassName>
      <StronglyTypedFileName>$(IntermediateOutputPath)ErrorMessages.Designer.cs</StronglyTypedFileName>
    </EmbeddedResource>

    <Compile Update="$(IntermediateOutputPath)ErrorMessages.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>ErrorMessages.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Resources.NeutralResourcesLanguageAttribute">
      <_Parameter1>en</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="TcfOss.DataStructures" />
    <PackageReference Include="TcfOss.StringEnumGenerator" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

</Project>