<Project>
    <PropertyGroup>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AnalysisMode>Recommended</AnalysisMode>
    </PropertyGroup>

    <PropertyGroup>
        <Authors>Thomas C. Flanagan</Authors>
        <Company>TcfOss</Company>
        <PackageProjectUrl>https://tcfoss.github.io/database-manager/</PackageProjectUrl>
        <RepositoryUrl>https://github.com/tcfoss/database-manager</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    </PropertyGroup>

    <PropertyGroup>
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
        <MinVerTagPrefix>v</MinVerTagPrefix>
    </PropertyGroup>

    <PropertyGroup Condition="'$(MSBuildProjectName)' != 'TcfOss.DatabaseManager.App'">
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <DebugType>portable</DebugType>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <Target Name="OverrideVersions" AfterTargets="MinVer">
        <PropertyGroup>
            <!-- Update only when major version changes -->
            <AssemblyVersion>0.1.0.0</AssemblyVersion>
        </PropertyGroup>
    </Target>

    <ItemGroup>
        <None Include="$(MSBuildProjectDirectory)/README.md" Pack="true" PackagePath="\" Condition="Exists('$(MSBuildProjectDirectory)/README.md')" />
    </ItemGroup>
</Project>