// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Entities;
using TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework;

namespace TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Configurations;

public class CharacterSetConfig : IEntityTypeConfiguration<CharacterSetEntity>
{
    public void Configure(EntityTypeBuilder<CharacterSetEntity> builder)
    {
        builder.ToTable("CHARACTER_SETS", "information_schema");

        builder.HasKey(e => e.CharacterSetName);

        builder.VarcharProperty(e => e.CharacterSetName, "CHARACTER_SET_NAME", 32, isRequired: true);
        builder.VarcharProperty(e => e.DefaultCollateName, "DEFAULT_COLLATE_NAME", 64, isRequired: true);
        builder.VarcharProperty(e => e.Description, "DESCRIPTION", 60, isRequired: true);
        builder.Property(e => e.Maxlen)
            .HasColumnName("MAXLEN");
    }
}
