// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Entities;
using TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework;

namespace TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Configurations;

public class CollationCharacterSetApplicabilityConfig : IEntityTypeConfiguration<CollationCharacterSetApplicabilityEntity>
{
    public void Configure(EntityTypeBuilder<CollationCharacterSetApplicabilityEntity> builder)
    {
        builder.ToTable("COLLATION_CHARACTER_SET_APPLICABILITY", "information_schema");

        builder.HasKey(e => e.FullCollationName);

        builder.VarcharProperty(e => e.CollationName, "COLLATION_NAME", 64, isRequired: true);
        builder.VarcharProperty(e => e.CharacterSetName, "CHARACTER_SET_NAME", 32, isRequired: true);
        builder.VarcharProperty(e => e.FullCollationName, "FULL_COLLATION_NAME", 64, isRequired: true);
        builder.Property(e => e.Id)
            .HasColumnName("ID");
        builder.VarcharProperty(e => e.IsDefault, "IS_DEFAULT", 3, isRequired: true);
    }
}
