// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Entities;
using TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework;

namespace TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Configurations;

public class ColumnConfig : IEntityTypeConfiguration<ColumnEntity>
{
    public void Configure(EntityTypeBuilder<ColumnEntity> builder)
    {
        builder.ToTable("COLUMNS", "information_schema");

        builder.HasKey(e => new { e.TableCatalog, e.TableSchema, e.TableName, e.ColumnName });

        builder.VarcharProperty(e => e.TableCatalog, "TABLE_CATALOG", 512, isRequired: true);
        builder.VarcharProperty(e => e.TableSchema, "TABLE_SCHEMA", 64, isRequired: true);
        builder.VarcharProperty(e => e.TableName, "TABLE_NAME", 64, isRequired: true);
        builder.VarcharProperty(e => e.ColumnName, "COLUMN_NAME", 64, isRequired: true);
        builder.Property(e => e.OrdinalPosition)
            .HasColumnName("ORDINAL_POSITION");
        builder.Property(e => e.ColumnDefault)
            .HasColumnName("COLUMN_DEFAULT")
            .HasColumnType("longtext");
        builder.VarcharProperty(e => e.IsNullable, "IS_NULLABLE", 3, isRequired: true);
        builder.VarcharProperty(e => e.DataType, "DATA_TYPE", 64, isRequired: true);
        builder.Property(e => e.CharacterMaximumLength)
            .HasColumnName("CHARACTER_MAXIMUM_LENGTH");
        builder.Property(e => e.CharacterOctetLength)
            .HasColumnName("CHARACTER_OCTET_LENGTH");
        builder.Property(e => e.NumericPrecision)
            .HasColumnName("NUMERIC_PRECISION");
        builder.Property(e => e.NumericScale)
            .HasColumnName("NUMERIC_SCALE");
        builder.Property(e => e.DatetimePrecision)
            .HasColumnName("DATETIME_PRECISION");
        builder.VarcharProperty(e => e.CharacterSetName, "CHARACTER_SET_NAME", 32, isRequired: false);
        builder.VarcharProperty(e => e.CollationName, "COLLATION_NAME", 64, isRequired: false);
        builder.Property(e => e.ColumnType)
            .HasColumnName("COLUMN_TYPE")
            .HasColumnType("longtext");
        builder.VarcharProperty(e => e.ColumnKey, "COLUMN_KEY", 3, isRequired: true);
        builder.VarcharProperty(e => e.Extra, "EXTRA", 80, isRequired: true);
        builder.VarcharProperty(e => e.Privileges, "PRIVILEGES", 80, isRequired: true);
        builder.VarcharProperty(e => e.ColumnComment, "COLUMN_COMMENT", 1024, isRequired: true);
        builder.VarcharProperty(e => e.IsGenerated, "IS_GENERATED", 6, isRequired: true);
        builder.Property(e => e.GenerationExpression)
            .HasColumnName("GENERATION_EXPRESSION")
            .HasColumnType("longtext");
    }
}
