// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Entities;
using TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework;

namespace TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Configurations;

public class EngineConfig : IEntityTypeConfiguration<EngineEntity>
{
    public void Configure(EntityTypeBuilder<EngineEntity> builder)
    {
        builder.ToTable("ENGINES", "information_schema");

        builder.HasKey(e => e.Engine);

        builder.VarcharProperty(e => e.Engine, "ENGINE", 64, isRequired: true);
        builder.VarcharProperty(e => e.Support, "SUPPORT", 8, isRequired: true);
        builder.VarcharProperty(e => e.Comment, "COMMENT", 160, isRequired: true);
        builder.VarcharProperty(e => e.Transactions, "TRANSACTIONS", 3, isRequired: false);
        builder.VarcharProperty(e => e.Xa, "XA", 3, isRequired: false);
        builder.VarcharProperty(e => e.Savepoints, "SAVEPOINTS", 3, isRequired: false);
    }
}
