// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Entities;
using TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework;

namespace TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Configurations;

public class EventConfig : IEntityTypeConfiguration<EventEntity>
{
    public void Configure(EntityTypeBuilder<EventEntity> builder)
    {
        builder.ToTable("EVENTS", "information_schema");

        builder.HasKey(e => new { e.EventCatalog, e.EventSchema, e.EventName });

        builder.VarcharProperty(e => e.EventCatalog, "EVENT_CATALOG", 64, isRequired: true);
        builder.VarcharProperty(e => e.EventSchema, "EVENT_SCHEMA", 64, isRequired: true);
        builder.VarcharProperty(e => e.EventName, "EVENT_NAME", 64, isRequired: true);
        builder.VarcharProperty(e => e.Definer, "DEFINER", 384, isRequired: true);
        builder.VarcharProperty(e => e.TimeZone, "TIME_ZONE", 64, isRequired: true);
        builder.VarcharProperty(e => e.EventBody, "EVENT_BODY", 8, isRequired: true);
        builder.Property(e => e.EventDefinition)
            .HasColumnName("EVENT_DEFINITION")
            .HasColumnType("longtext");
        builder.VarcharProperty(e => e.EventType, "EVENT_TYPE", 9, isRequired: true);
        builder.Property(e => e.ExecuteAt)
            .HasColumnName("EXECUTE_AT")
            .HasColumnType("datetime");
        builder.VarcharProperty(e => e.IntervalValue, "INTERVAL_VALUE", 256, isRequired: false);
        builder.VarcharProperty(e => e.IntervalField, "INTERVAL_FIELD", 18, isRequired: false);
        builder.VarcharProperty(e => e.SqlMode, "SQL_MODE", 8192, isRequired: true);
        builder.Property(e => e.Starts)
            .HasColumnName("STARTS")
            .HasColumnType("datetime");
        builder.Property(e => e.Ends)
            .HasColumnName("ENDS")
            .HasColumnType("datetime");
        builder.VarcharProperty(e => e.Status, "STATUS", 18, isRequired: true);
        builder.VarcharProperty(e => e.OnCompletion, "ON_COMPLETION", 12, isRequired: true);
        builder.Property(e => e.Created)
            .HasColumnName("CREATED")
            .HasColumnType("datetime");
        builder.Property(e => e.LastAltered)
            .HasColumnName("LAST_ALTERED")
            .HasColumnType("datetime");
        builder.Property(e => e.LastExecuted)
            .HasColumnName("LAST_EXECUTED")
            .HasColumnType("datetime");
        builder.VarcharProperty(e => e.EventComment, "EVENT_COMMENT", 64, isRequired: true);
        builder.Property(e => e.Originator)
            .HasColumnName("ORIGINATOR");
        builder.VarcharProperty(e => e.CharacterSetClient, "CHARACTER_SET_CLIENT", 32, isRequired: true);
        builder.VarcharProperty(e => e.CollationConnection, "COLLATION_CONNECTION", 64, isRequired: true);
        builder.VarcharProperty(e => e.DatabaseCollation, "DATABASE_COLLATION", 64, isRequired: true);
    }
}
