// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Entities;
using TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework;

namespace TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Configurations;

public class ParameterConfig : IEntityTypeConfiguration<ParameterEntity>
{
    public void Configure(EntityTypeBuilder<ParameterEntity> builder)
    {
        builder.ToTable("PARAMETERS", "information_schema");

        builder.HasKey(e => new { e.SpecificCatalog, e.SpecificSchema, e.SpecificName, e.OrdinalPosition });

        builder.VarcharProperty(e => e.SpecificCatalog, "SPECIFIC_CATALOG", 512, isRequired: true);
        builder.VarcharProperty(e => e.SpecificSchema, "SPECIFIC_SCHEMA", 64, isRequired: true);
        builder.VarcharProperty(e => e.SpecificName, "SPECIFIC_NAME", 64, isRequired: true);
        builder.Property(e => e.OrdinalPosition)
            .HasColumnName("ORDINAL_POSITION");
        builder.VarcharProperty(e => e.ParameterMode, "PARAMETER_MODE", 5, isRequired: false);
        builder.VarcharProperty(e => e.ParameterName, "PARAMETER_NAME", 64, isRequired: false);
        builder.VarcharProperty(e => e.DataType, "DATA_TYPE", 64, isRequired: true);
        builder.Property(e => e.CharacterMaximumLength)
            .HasColumnName("CHARACTER_MAXIMUM_LENGTH");
        builder.Property(e => e.CharacterOctetLength)
            .HasColumnName("CHARACTER_OCTET_LENGTH");
        builder.Property(e => e.NumericPrecision)
            .HasColumnName("NUMERIC_PRECISION");
        builder.Property(e => e.NumericScale)
            .HasColumnName("NUMERIC_SCALE");
        builder.Property(e => e.DatetimePrecision)
            .HasColumnName("DATETIME_PRECISION");
        builder.VarcharProperty(e => e.CharacterSetName, "CHARACTER_SET_NAME", 64, isRequired: false);
        builder.VarcharProperty(e => e.CollationName, "COLLATION_NAME", 64, isRequired: false);
        builder.Property(e => e.DtdIdentifier)
            .HasColumnName("DTD_IDENTIFIER")
            .HasColumnType("longtext");
        builder.VarcharProperty(e => e.RoutineType, "ROUTINE_TYPE", 9, isRequired: true);
    }
}
