// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Entities;
using TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework;

namespace TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Configurations;

public class ReferentialConstraintConfig : IEntityTypeConfiguration<ReferentialConstraintEntity>
{
    public void Configure(EntityTypeBuilder<ReferentialConstraintEntity> builder)
    {
        builder.ToTable("REFERENTIAL_CONSTRAINTS", "information_schema");

        builder.HasKey(e => new { e.ConstraintCatalog, e.ConstraintSchema, e.ConstraintName });

        builder.VarcharProperty(e => e.ConstraintCatalog, "CONSTRAINT_CATALOG", 512, isRequired: true);
        builder.VarcharProperty(e => e.ConstraintSchema, "CONSTRAINT_SCHEMA", 64, isRequired: true);
        builder.VarcharProperty(e => e.ConstraintName, "CONSTRAINT_NAME", 64, isRequired: true);
        builder.VarcharProperty(e => e.UniqueConstraintCatalog, "UNIQUE_CONSTRAINT_CATALOG", 512, isRequired: true);
        builder.VarcharProperty(e => e.UniqueConstraintSchema, "UNIQUE_CONSTRAINT_SCHEMA", 64, isRequired: true);
        builder.VarcharProperty(e => e.UniqueConstraintName, "UNIQUE_CONSTRAINT_NAME", 64, isRequired: false);
        builder.VarcharProperty(e => e.MatchOption, "MATCH_OPTION", 64, isRequired: true);
        builder.VarcharProperty(e => e.UpdateRule, "UPDATE_RULE", 64, isRequired: true);
        builder.VarcharProperty(e => e.DeleteRule, "DELETE_RULE", 64, isRequired: true);
        builder.VarcharProperty(e => e.TableName, "TABLE_NAME", 64, isRequired: true);
        builder.VarcharProperty(e => e.ReferencedTableName, "REFERENCED_TABLE_NAME", 64, isRequired: false);
    }
}
