// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Entities;
using TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework;

namespace TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Configurations;

public class RoutineConfig : IEntityTypeConfiguration<RoutineEntity>
{
    public void Configure(EntityTypeBuilder<RoutineEntity> builder)
    {
        builder.ToTable("ROUTINES", "information_schema");

        builder.HasKey(e => new { e.RoutineCatalog, e.RoutineSchema, e.RoutineName });

        builder.VarcharProperty(e => e.SpecificName, "SPECIFIC_NAME", 64, isRequired: true);
        builder.VarcharProperty(e => e.RoutineCatalog, "ROUTINE_CATALOG", 512, isRequired: true);
        builder.VarcharProperty(e => e.RoutineSchema, "ROUTINE_SCHEMA", 64, isRequired: true);
        builder.VarcharProperty(e => e.RoutineName, "ROUTINE_NAME", 64, isRequired: true);
        builder.VarcharProperty(e => e.RoutineType, "ROUTINE_TYPE", 13, isRequired: true);
        builder.VarcharProperty(e => e.DataType, "DATA_TYPE", 64, isRequired: true);
        builder.Property(e => e.CharacterMaximumLength)
            .HasColumnName("CHARACTER_MAXIMUM_LENGTH");
        builder.Property(e => e.CharacterOctetLength)
            .HasColumnName("CHARACTER_OCTET_LENGTH");
        builder.Property(e => e.NumericPrecision)
            .HasColumnName("NUMERIC_PRECISION");
        builder.Property(e => e.NumericScale)
            .HasColumnName("NUMERIC_SCALE");
        builder.Property(e => e.DatetimePrecision)
            .HasColumnName("DATETIME_PRECISION");
        builder.VarcharProperty(e => e.CharacterSetName, "CHARACTER_SET_NAME", 64, isRequired: false);
        builder.VarcharProperty(e => e.CollationName, "COLLATION_NAME", 64, isRequired: false);
        builder.Property(e => e.DtdIdentifier)
            .HasColumnName("DTD_IDENTIFIER")
            .HasColumnType("longtext");
        builder.VarcharProperty(e => e.RoutineBody, "ROUTINE_BODY", 8, isRequired: true);
        builder.Property(e => e.RoutineDefinition)
            .HasColumnName("ROUTINE_DEFINITION")
            .HasColumnType("longtext");
        builder.VarcharProperty(e => e.ExternalName, "EXTERNAL_NAME", 64, isRequired: false);
        builder.VarcharProperty(e => e.ExternalLanguage, "EXTERNAL_LANGUAGE", 64, isRequired: false);
        builder.VarcharProperty(e => e.ParameterStyle, "PARAMETER_STYLE", 8, isRequired: true);
        builder.VarcharProperty(e => e.IsDeterministic, "IS_DETERMINISTIC", 3, isRequired: true);
        builder.VarcharProperty(e => e.SqlDataAccess, "SQL_DATA_ACCESS", 64, isRequired: true);
        builder.VarcharProperty(e => e.SqlPath, "SQL_PATH", 64, isRequired: false);
        builder.VarcharProperty(e => e.SecurityType, "SECURITY_TYPE", 7, isRequired: true);
        builder.Property(e => e.Created)
            .HasColumnName("CREATED")
            .HasColumnType("datetime");
        builder.Property(e => e.LastAltered)
            .HasColumnName("LAST_ALTERED")
            .HasColumnType("datetime");
        builder.VarcharProperty(e => e.SqlMode, "SQL_MODE", 8192, isRequired: true);
        builder.Property(e => e.RoutineComment)
            .HasColumnName("ROUTINE_COMMENT")
            .HasColumnType("longtext");
        builder.VarcharProperty(e => e.Definer, "DEFINER", 384, isRequired: true);
        builder.VarcharProperty(e => e.CharacterSetClient, "CHARACTER_SET_CLIENT", 32, isRequired: true);
        builder.VarcharProperty(e => e.CollationConnection, "COLLATION_CONNECTION", 64, isRequired: true);
        builder.VarcharProperty(e => e.DatabaseCollation, "DATABASE_COLLATION", 64, isRequired: true);
    }
}
