// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Entities;
using TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework;

namespace TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Configurations;

public class SchemataConfig : IEntityTypeConfiguration<SchemataEntity>
{
    public void Configure(EntityTypeBuilder<SchemataEntity> builder)
    {
        builder.ToTable("SCHEMATA", "information_schema");

        builder.HasKey(e => new { e.CatalogName, e.SchemaName });

        builder.VarcharProperty(e => e.CatalogName, "CATALOG_NAME", 512, isRequired: true);
        builder.VarcharProperty(e => e.SchemaName, "SCHEMA_NAME", 64, isRequired: true);
        builder.VarcharProperty(e => e.DefaultCharacterSetName, "DEFAULT_CHARACTER_SET_NAME", 32, isRequired: true);
        builder.VarcharProperty(e => e.DefaultCollationName, "DEFAULT_COLLATION_NAME", 64, isRequired: true);
        builder.VarcharProperty(e => e.SqlPath, "SQL_PATH", 512, isRequired: false);
        builder.VarcharProperty(e => e.SchemaComment, "SCHEMA_COMMENT", 1024, isRequired: true);
    }
}
