// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Entities;
using TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework;

namespace TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Configurations;

public class TableConstraintConfig : IEntityTypeConfiguration<TableConstraintEntity>
{
    public void Configure(EntityTypeBuilder<TableConstraintEntity> builder)
    {
        builder.ToTable("TABLE_CONSTRAINTS", "information_schema");

        builder.HasKey(e => new { e.ConstraintCatalog, e.ConstraintSchema, e.ConstraintName, e.TableName });

        builder.VarcharProperty(e => e.ConstraintCatalog, "CONSTRAINT_CATALOG", 512, isRequired: true);
        builder.VarcharProperty(e => e.ConstraintSchema, "CONSTRAINT_SCHEMA", 64, isRequired: true);
        builder.VarcharProperty(e => e.ConstraintName, "CONSTRAINT_NAME", 64, isRequired: true);
        builder.VarcharProperty(e => e.TableSchema, "TABLE_SCHEMA", 64, isRequired: true);
        builder.VarcharProperty(e => e.TableName, "TABLE_NAME", 64, isRequired: true);
        builder.VarcharProperty(e => e.ConstraintType, "CONSTRAINT_TYPE", 64, isRequired: true);
    }
}
