// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Entities;
using TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework;

namespace TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Configurations;

public class TriggerConfig : IEntityTypeConfiguration<TriggerEntity>
{
    public void Configure(EntityTypeBuilder<TriggerEntity> builder)
    {
        builder.ToTable("TRIGGERS", "information_schema");

        builder.HasKey(e => new { e.TriggerCatalog, e.TriggerSchema, e.TriggerName });

        builder.VarcharProperty(e => e.TriggerCatalog, "TRIGGER_CATALOG", 512, isRequired: true);
        builder.VarcharProperty(e => e.TriggerSchema, "TRIGGER_SCHEMA", 64, isRequired: true);
        builder.VarcharProperty(e => e.TriggerName, "TRIGGER_NAME", 64, isRequired: true);
        builder.VarcharProperty(e => e.EventManipulation, "EVENT_MANIPULATION", 6, isRequired: true);
        builder.VarcharProperty(e => e.EventObjectCatalog, "EVENT_OBJECT_CATALOG", 512, isRequired: true);
        builder.VarcharProperty(e => e.EventObjectSchema, "EVENT_OBJECT_SCHEMA", 64, isRequired: true);
        builder.VarcharProperty(e => e.EventObjectTable, "EVENT_OBJECT_TABLE", 64, isRequired: true);
        builder.Property(e => e.ActionOrder)
            .HasColumnName("ACTION_ORDER");
        builder.Property(e => e.ActionCondition)
            .HasColumnName("ACTION_CONDITION")
            .HasColumnType("longtext");
        builder.Property(e => e.ActionStatement)
            .HasColumnName("ACTION_STATEMENT")
            .HasColumnType("longtext");
        builder.VarcharProperty(e => e.ActionOrientation, "ACTION_ORIENTATION", 9, isRequired: true);
        builder.VarcharProperty(e => e.ActionTiming, "ACTION_TIMING", 6, isRequired: true);
        builder.VarcharProperty(e => e.ActionReferenceOldTable, "ACTION_REFERENCE_OLD_TABLE", 64, isRequired: false);
        builder.VarcharProperty(e => e.ActionReferenceNewTable, "ACTION_REFERENCE_NEW_TABLE", 64, isRequired: false);
        builder.VarcharProperty(e => e.ActionReferenceOldRow, "ACTION_REFERENCE_OLD_ROW", 3, isRequired: true);
        builder.VarcharProperty(e => e.ActionReferenceNewRow, "ACTION_REFERENCE_NEW_ROW", 3, isRequired: true);
        builder.Property(e => e.Created)
            .HasColumnName("CREATED")
            .HasColumnType("datetime(2)");
        builder.VarcharProperty(e => e.SqlMode, "SQL_MODE", 8192, isRequired: true);
        builder.VarcharProperty(e => e.Definer, "DEFINER", 384, isRequired: true);
        builder.VarcharProperty(e => e.CharacterSetClient, "CHARACTER_SET_CLIENT", 32, isRequired: true);
        builder.VarcharProperty(e => e.CollationConnection, "COLLATION_CONNECTION", 64, isRequired: true);
        builder.VarcharProperty(e => e.DatabaseCollation, "DATABASE_COLLATION", 64, isRequired: true);
    }
}
