// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Entities;
using TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework;

namespace TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Configurations;

public class ViewConfig : IEntityTypeConfiguration<ViewEntity>
{
    public void Configure(EntityTypeBuilder<ViewEntity> builder)
    {
        builder.ToTable("VIEWS", "information_schema");

        builder.HasKey(e => new { e.TableCatalog, e.TableSchema, e.TableName });

        builder.VarcharProperty(e => e.TableCatalog, "TABLE_CATALOG", 512, isRequired: true);
        builder.VarcharProperty(e => e.TableSchema, "TABLE_SCHEMA", 64, isRequired: true);
        builder.VarcharProperty(e => e.TableName, "TABLE_NAME", 64, isRequired: true);
        builder.Property(e => e.ViewDefinition)
            .HasColumnName("VIEW_DEFINITION")
            .HasColumnType("longtext");
        builder.VarcharProperty(e => e.CheckOption, "CHECK_OPTION", 8, isRequired: true);
        builder.VarcharProperty(e => e.IsUpdatable, "IS_UPDATABLE", 3, isRequired: true);
        builder.VarcharProperty(e => e.Definer, "DEFINER", 384, isRequired: true);
        builder.VarcharProperty(e => e.SecurityType, "SECURITY_TYPE", 7, isRequired: true);
        builder.VarcharProperty(e => e.CharacterSetClient, "CHARACTER_SET_CLIENT", 32, isRequired: true);
        builder.VarcharProperty(e => e.CollationConnection, "COLLATION_CONNECTION", 64, isRequired: true);
        builder.VarcharProperty(e => e.Algorithm, "ALGORITHM", 10, isRequired: true);
    }
}
