"""Generate C# entities from database tables."""

import os
from pathlib import Path
from typing import Any, Callable
from attrs import define as _define
from dbman_dev.containers import db_container
from dbman_dev.csharp_code_generation.entity_model import EntityModel
from dbman_dev.db.show_fields_result import ShowFieldsResult as _ShowFieldResult
from dbman_dev.utilities.text_conversion import (
    snake_to_pascal as _snake_to_pascal,
    pluralize as _pluralize,
)
from dbman_dev.csharp_code_generation.model_config import ModelConfig as _ModelConfig

_ENTITY_TEMPLATE = """// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

namespace {namespace};

public class {class_name}Entity
{{
    {properties}
}}
"""

_CONFIG_TEMPLATE = """// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using {entity_namespace};{extensions_import}

namespace {namespace};

public class {class_name}Config : IEntityTypeConfiguration<{class_name}Entity>
{{
    public void Configure(EntityTypeBuilder<{class_name}Entity> builder)
    {{
        builder.ToTable("{table_name}", "{schema}");

{config_lines}
    }}
}}
"""

_CONTEXT_TEMPLATE = """// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using System.Reflection;
using Microsoft.EntityFrameworkCore;
using {entity_namespace};

namespace {namespace};

public class {context_class} : DbContext
{{
{db_sets}

    public {context_class}(DbContextOptions options)
        : base(options)
    {{
    }}

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {{
        base.OnModelCreating(modelBuilder);
        modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());
    }}
}}
"""


class EntityGenerator:
    """Generates C# entities from database tables."""

    def __init__(
        self,
        image: str,
        environment: dict[str, str],
        output_root: Path,
        root_namespace: str,
        entity_namespace: str,
        config_namespace: str,
        context_class: str,
        config_import_selector: Callable[[str, list[str]], str],
    ):
        self.container = db_container.MySqlContainer(
            image=image,
            port=3309,
            environment=environment,
        )

        self.root_namespace: str = root_namespace
        self.entity_namespace: str = entity_namespace
        self.config_namespace: str = config_namespace
        self.output_root: Path = output_root
        self.entity_dir: Path = output_root / "Entities"
        self.config_dir: Path = output_root / "Configurations"
        self.context_class: str = context_class
        self.config_import_selector: Callable[[str, list[str]], str] = config_import_selector

    def __get_key(self, conversion_config: _ModelConfig) -> list[str]:
        """Get a unique key for the information schema configuration."""

        result = []
        pk_components = conversion_config.key_columns
        if pk_components and len(pk_components) == 1:
            field_name = _snake_to_pascal(pk_components[0])
            result.append(f"        builder.HasKey(e => e.{field_name});")
            result.append("")
        elif pk_components:
            pk_field_names = ", ".join(["e." + _snake_to_pascal(x) for x in pk_components])
            result.append(f"        builder.HasKey(e => new {{ {pk_field_names} }});")
            result.append("")

        return result

    def __get_column_model(
        self, field: tuple[Any, ...], conversion_config: _ModelConfig
    ) -> EntityModel | None:
        """Return an EntityModel from a database field tuple."""

        model = _ShowFieldResult.from_row(field)
        if conversion_config.ignored_columns and model.field in conversion_config.ignored_columns:
            return None

        if model.field in conversion_config.key_columns:
            model.nullable = False  # Key columns should not be nullable

        if (
            conversion_config.not_null_overrides
            and model.field in conversion_config.not_null_overrides
        ):
            model.nullable = False

        return model.to_cs_model()

    def __generate_entity_for_table(
        self,
        container: db_container.MySqlContainer,
        schema: str,
        conversion_config: _ModelConfig,
        table_name: str,
        model_name: str,
    ) -> None:
        """Generate C# entity and configuration for a specific table."""

        print(f"Generating entity for table: {conversion_config.table_name}")

        entity_lines: list[str] = []
        config_lines: list[str] = []

        config_lines.extend(self.__get_key(conversion_config))

        fields = container.query(f"SHOW FIELDS FROM `{schema}`.`{table_name}`;")
        for field in fields:
            entity_model = self.__get_column_model(field, conversion_config)
            if not entity_model:
                continue
            entity_lines.append(entity_model.get_entity_line())
            config_lines.append("        " + entity_model.get_config_line())

        with open(
            os.path.join(self.entity_dir, f"{model_name}Entity.cs"), "w", encoding="utf-8"
        ) as entity_file:
            entity_file.write(
                _ENTITY_TEMPLATE.format(
                    namespace=self.entity_namespace,
                    class_name=model_name,
                    properties="\n    ".join(entity_lines),
                )
            )

        with open(
            os.path.join(self.config_dir, f"{model_name}Config.cs"), "w", encoding="utf-8"
        ) as config_file:
            extensions_import = self.config_import_selector(self.config_namespace, config_lines)
            if extensions_import:
                extensions_import = "\n" + extensions_import

            config_file.write(
                _CONFIG_TEMPLATE.format(
                    namespace=self.config_namespace,
                    class_name=model_name,
                    entity_namespace=self.entity_namespace,
                    table_name=table_name,
                    schema=schema,
                    config_lines="\n".join(config_lines),
                    extensions_import=extensions_import,
                )
            )

    def generate_entities(self, schema: str, tables: list[_ModelConfig]) -> None:
        """Generate C# entity lines and configuration lines."""

        if not self.entity_dir.exists():
            self.entity_dir.mkdir(parents=True)

        if not self.config_dir.exists():
            self.config_dir.mkdir(parents=True)

        db_set_lines: list[str] = []

        with self.container as c:
            assert c.container is not None
            print("Container started with ID:", c.container.id)
            print("Container status:", c.container.status)

            for table_config in tables:
                table_name = table_config.table_name
                model_name = table_config.model_name_override or _snake_to_pascal(table_name)
                if table_config.plural_name_override:
                    plural_model_name = table_config.plural_name_override
                else:
                    plural_model_name = _pluralize(model_name)

                db_set_lines.append(
                    f"    public DbSet<{model_name}Entity> {plural_model_name} {{ get; set; }}"
                )

                self.__generate_entity_for_table(c, schema, table_config, table_name, model_name)

        with open(
            self.output_root / f"{self.context_class}.cs", "w", encoding="utf-8"
        ) as context_file:
            context_file.write(
                _CONTEXT_TEMPLATE.format(
                    namespace=self.root_namespace,
                    context_class=self.context_class,
                    entity_namespace=self.entity_namespace,
                    db_sets="\n".join(db_set_lines),
                )
            )


def _default_config_import_selector(_namespace: str, _config_lines: list[str]) -> str:
    """Default function to select necessary imports for configuration files."""

    return ""


@_define
class EntityGeneratorConfig:
    """Configuration for entity generator."""

    dialect: str
    image: str
    schema: str
    tables: list[_ModelConfig]
    output_root: Path
    base_namespace: str
    entity_namespace: str
    config_namespace: str
    context_class: str
    environment: dict[str, str]
    config_import_selector: Callable[[str, list[str]], str] = _default_config_import_selector


def run(args: EntityGeneratorConfig) -> None:
    """Run the entity generation process."""

    print(f"Writing entities in '{args.output_root}'...")

    generator = EntityGenerator(
        image=args.image,
        environment=args.environment,
        output_root=args.output_root,
        root_namespace=args.base_namespace,
        entity_namespace=args.entity_namespace,
        config_namespace=args.config_namespace,
        context_class=args.context_class,
        config_import_selector=args.config_import_selector,
    )

    generator.generate_entities(args.schema, args.tables)
    print("Entity generation completed.")
