"""Generate data for testing."""

from pathlib import Path
from attrs import define as _define
from dbman_dev.containers import db_container
from dbman_dev.csharp_code_generation.model_config import ModelConfig as _ModelConfig
from dbman_dev.db.get_show_fields_results import get_show_fields_results
from dbman_dev.db import defaults as db_defaults
from dbman_dev.utilities import linq, text_conversion


_FUNC_TEMPLATE = """
    public static {entity_type}Entity[] Get{entity_type}Entities()
    {{
        return [
{entity_rows}
        ];
    }}
"""

_CLASS_TEMPLATE = """// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using {entity_namespace};

namespace {output_namespace};

public static class {dialect}ContextTestData
{{
{functions}
}}
"""


class TestDataGenerator:
    """Generate test data for some RDBMS."""

    def __init__(
        self,
        image: str,
        tables: list[_ModelConfig],
        environment: dict[str, str],
        source_path: Path,
        output_path: Path,
    ):

        self.container = db_container.MySqlContainer(
            image=image,
            port=3309,
            environment=environment,
        )

        self.tables = tables
        self.source_path = source_path
        self.output_path = output_path

    def __construct_columns_and_data_query(
        self,
        container: db_container.MySqlContainer,
        model_config: _ModelConfig,
        schemas: list[str],
    ):
        """Return SQL to query an information_schema table."""
        columns = get_show_fields_results(container, "information_schema", model_config.table_name)

        ignored_columns = set(model_config.ignored_columns or [])

        columns = [x for x in columns if x.column_name not in ignored_columns]

        schema_column = linq.first_or_default(
            columns, lambda x: x.column_name.lower().endswith("_schema")
        )
        select_fields = ", ".join(x.column_name for x in columns)
        query = f"SELECT {select_fields} FROM `{model_config.table_name}`"
        if schema_column:
            schema_names = ",".join([f"'{x}'" for x in schemas])
            query += f" WHERE `{schema_column.column_name}` IN ({schema_names})"

        return (columns, query)

    def generate_data(
        self, schemas: list[str], initialization_scripts: list[str]
    ) -> dict[str, list[str]]:
        """Generate and insert test data into the database."""

        with self.container as c:
            assert c.container is not None, "Container should be running"
            print("Container started with ID:", c.container.id)
            print("Container status:", c.container.status)

            print("Creating directory in the container...")
            c.exec_run("mkdir /InitialSchemas")

            print("Uploading initial schema files...")
            c.upload_file(source_path=str(self.source_path), target_path="/InitialSchemas")

            print("Running initialization scripts...")
            for script in initialization_scripts:
                print(f"Running script: {script}")
                _ = c.exec_run(["bash", script], workdir="/InitialSchemas/Init")

            data_sets = {}

            for table_config in self.tables:

                columns, query = self.__construct_columns_and_data_query(c, table_config, schemas)

                print("Executing query:", query)

                object_name = table_config.model_name_override or text_conversion.snake_to_pascal(
                    table_config.table_name
                )

                results = c.query(query)

                table_data = []
                for row in results:
                    object_line = f"            new {object_name}Entity {{ "
                    for col, val in zip(columns, row):
                        object_line += f"{col.property_name} = {col.get_value(val)}, "
                    object_line += "},"
                    table_data.append(object_line)

                data_sets[object_name] = table_data

        return data_sets


@_define
class ModelDataLoaderConfig:
    """Configuration for model data loader."""

    dialect: str
    source_path: Path
    output_path: Path
    image: str
    schemas: list[str]
    tables: list[_ModelConfig]
    entity_namespace: str
    output_namespace: str
    initialization_scripts: list[str] = []
    environment: dict[str, str] = db_defaults.ENVIRONMENT


def run(args: ModelDataLoaderConfig) -> None:
    """Run the data source generation process."""

    generator = TestDataGenerator(
        image=args.image,
        environment=args.environment,
        tables=args.tables,
        source_path=args.source_path,
        output_path=args.output_path,
    )

    data_sets = generator.generate_data(args.schemas, args.initialization_scripts)

    function_strings = [
        _FUNC_TEMPLATE.format(entity_type=table_name, entity_rows="\n".join(lines))
        for table_name, lines in data_sets.items()
    ]

    class_string = _CLASS_TEMPLATE.format(
        dialect=args.dialect,
        entity_namespace=args.entity_namespace,
        output_namespace=args.output_namespace,
        functions="".join(function_strings),
    )

    with open(args.output_path, "w", encoding="utf-8") as f:
        f.write(class_string)
