// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using System.Reflection;
using Microsoft.EntityFrameworkCore;
using TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Entities;

namespace TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework;

public class InfoSchemaContext : DbContext
{
    public DbSet<TableEntity> Tables { get; set; }
    public DbSet<ColumnEntity> Columns { get; set; }
    public DbSet<SchemataEntity> Schematas { get; set; }
    public DbSet<TableConstraintEntity> TableConstraints { get; set; }
    public DbSet<ReferentialConstraintEntity> ReferentialConstraints { get; set; }
    public DbSet<StatisticsEntity> Statistics { get; set; }
    public DbSet<KeyColumnUsageEntity> KeyColumnUsages { get; set; }
    public DbSet<CheckConstraintEntity> CheckConstraints { get; set; }
    public DbSet<RoutineEntity> Routines { get; set; }
    public DbSet<ParameterEntity> Parameters { get; set; }
    public DbSet<TriggerEntity> Triggers { get; set; }
    public DbSet<ViewEntity> Views { get; set; }
    public DbSet<EventEntity> Events { get; set; }
    public DbSet<CharacterSetEntity> CharacterSets { get; set; }
    public DbSet<CollationCharacterSetApplicabilityEntity> CollationCharacterSetApplicabilities { get; set; }
    public DbSet<EngineEntity> Engines { get; set; }

    public InfoSchemaContext(DbContextOptions options)
        : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());
    }
}
