// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Entities;

namespace TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Configurations;

public class CheckConstraintConfig : IEntityTypeConfiguration<CheckConstraintEntity>
{
    public void Configure(EntityTypeBuilder<CheckConstraintEntity> builder)
    {
        builder.ToTable("CHECK_CONSTRAINTS", "information_schema");

        builder.HasKey(e => new { e.ConstraintCatalog, e.ConstraintSchema, e.ConstraintName });

        builder.VarcharProperty(e => e.ConstraintCatalog, "CONSTRAINT_CATALOG", 64, isRequired: true);
        builder.VarcharProperty(e => e.ConstraintSchema, "CONSTRAINT_SCHEMA", 64, isRequired: true);
        builder.VarcharProperty(e => e.ConstraintName, "CONSTRAINT_NAME", 64, isRequired: true);
        builder.Property(e => e.CheckClause)
            .HasColumnName("CHECK_CLAUSE")
            .HasColumnType("longtext");
    }
}
