// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Entities;

namespace TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Configurations;

public class EventConfig : IEntityTypeConfiguration<EventEntity>
{
    public void Configure(EntityTypeBuilder<EventEntity> builder)
    {
        builder.ToTable("EVENTS", "information_schema");

        builder.HasKey(e => new { e.EventCatalog, e.EventSchema, e.EventName });

        builder.VarcharProperty(e => e.EventCatalog, "EVENT_CATALOG", 64, isRequired: true);
        builder.VarcharProperty(e => e.EventSchema, "EVENT_SCHEMA", 64, isRequired: true);
        builder.VarcharProperty(e => e.EventName, "EVENT_NAME", 64, isRequired: true);
        builder.VarcharProperty(e => e.Definer, "DEFINER", 288, isRequired: true);
        builder.VarcharProperty(e => e.TimeZone, "TIME_ZONE", 64, isRequired: true);
        builder.VarcharProperty(e => e.EventBody, "EVENT_BODY", 3, isRequired: true);
        builder.Property(e => e.EventDefinition)
            .HasColumnName("EVENT_DEFINITION")
            .HasColumnType("longtext");
        builder.VarcharProperty(e => e.EventType, "EVENT_TYPE", 9, isRequired: true);
        builder.Property(e => e.ExecuteAt)
            .HasColumnName("EXECUTE_AT")
            .HasColumnType("datetime");
        builder.VarcharProperty(e => e.IntervalValue, "INTERVAL_VALUE", 256, isRequired: false);
        builder.Property(e => e.IntervalField)
            .HasColumnName("INTERVAL_FIELD")
            .HasColumnType("enum('YEAR','QUARTER','MONTH','DAY','HOUR','MINUTE','WEEK','SECOND','MICROSECOND','YEAR_MONTH','DAY_HOUR','DAY_MINUTE','DAY_SECOND','HOUR_MINUTE','HOUR_SECOND','MINUTE_SECOND','DAY_MICROSECOND','HOUR_MICROSECOND','MINUTE_MICROSECOND','SECOND_MICROSECOND')");
        builder.Property(e => e.SqlMode)
            .HasColumnName("SQL_MODE")
            .HasColumnType("set('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','NOT_USED','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','NOT_USED_9','NOT_USED_10','NOT_USED_11','NOT_USED_12','NOT_USED_13','NOT_USED_14','NOT_USED_15','NOT_USED_16','NOT_USED_17','NOT_USED_18','ANSI','NO_AUTO_VALUE_ON_ZERO','NO_BACKSLASH_ESCAPES','STRICT_TRANS_TABLES','STRICT_ALL_TABLES','NO_ZERO_IN_DATE','NO_ZERO_DATE','ALLOW_INVALID_DATES','ERROR_FOR_DIVISION_BY_ZERO','TRADITIONAL','NOT_USED_29','HIGH_NOT_PRECEDENCE','NO_ENGINE_SUBSTITUTION','PAD_CHAR_TO_FULL_LENGTH','TIME_TRUNCATE_FRACTIONAL')");
        builder.Property(e => e.Starts)
            .HasColumnName("STARTS")
            .HasColumnType("datetime");
        builder.Property(e => e.Ends)
            .HasColumnName("ENDS")
            .HasColumnType("datetime");
        builder.VarcharProperty(e => e.Status, "STATUS", 21, isRequired: true);
        builder.VarcharProperty(e => e.OnCompletion, "ON_COMPLETION", 12, isRequired: true);
        builder.Property(e => e.Created)
            .HasColumnName("CREATED")
            .HasColumnType("timestamp");
        builder.Property(e => e.LastAltered)
            .HasColumnName("LAST_ALTERED")
            .HasColumnType("timestamp");
        builder.Property(e => e.LastExecuted)
            .HasColumnName("LAST_EXECUTED")
            .HasColumnType("datetime");
        builder.VarcharProperty(e => e.EventComment, "EVENT_COMMENT", 2048, isRequired: true);
        builder.Property(e => e.Originator)
            .HasColumnName("ORIGINATOR");
        builder.VarcharProperty(e => e.CharacterSetClient, "CHARACTER_SET_CLIENT", 64, isRequired: true);
        builder.VarcharProperty(e => e.CollationConnection, "COLLATION_CONNECTION", 64, isRequired: true);
        builder.VarcharProperty(e => e.DatabaseCollation, "DATABASE_COLLATION", 64, isRequired: true);
    }
}
