// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Entities;

namespace TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Configurations;

public class KeyColumnUsageConfig : IEntityTypeConfiguration<KeyColumnUsageEntity>
{
    public void Configure(EntityTypeBuilder<KeyColumnUsageEntity> builder)
    {
        builder.ToTable("KEY_COLUMN_USAGE", "information_schema");

        builder.HasKey(e => new { e.ConstraintCatalog, e.ConstraintSchema, e.ConstraintName, e.TableName, e.OrdinalPosition });

        builder.VarcharProperty(e => e.ConstraintCatalog, "CONSTRAINT_CATALOG", 64, isRequired: true);
        builder.VarcharProperty(e => e.ConstraintSchema, "CONSTRAINT_SCHEMA", 64, isRequired: true);
        builder.VarcharProperty(e => e.ConstraintName, "CONSTRAINT_NAME", 64, isRequired: true);
        builder.VarcharProperty(e => e.TableCatalog, "TABLE_CATALOG", 64, isRequired: true);
        builder.VarcharProperty(e => e.TableSchema, "TABLE_SCHEMA", 64, isRequired: true);
        builder.VarcharProperty(e => e.TableName, "TABLE_NAME", 64, isRequired: true);
        builder.VarcharProperty(e => e.ColumnName, "COLUMN_NAME", 64, isRequired: true);
        builder.Property(e => e.OrdinalPosition)
            .HasColumnName("ORDINAL_POSITION");
        builder.Property(e => e.PositionInUniqueConstraint)
            .HasColumnName("POSITION_IN_UNIQUE_CONSTRAINT");
        builder.VarcharProperty(e => e.ReferencedTableSchema, "REFERENCED_TABLE_SCHEMA", 64, isRequired: false);
        builder.VarcharProperty(e => e.ReferencedTableName, "REFERENCED_TABLE_NAME", 64, isRequired: false);
        builder.VarcharProperty(e => e.ReferencedColumnName, "REFERENCED_COLUMN_NAME", 64, isRequired: false);
    }
}
