// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Entities;

namespace TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Configurations;

public class ReferentialConstraintConfig : IEntityTypeConfiguration<ReferentialConstraintEntity>
{
    public void Configure(EntityTypeBuilder<ReferentialConstraintEntity> builder)
    {
        builder.ToTable("REFERENTIAL_CONSTRAINTS", "information_schema");

        builder.HasKey(e => new { e.ConstraintCatalog, e.ConstraintSchema, e.ConstraintName });

        builder.VarcharProperty(e => e.ConstraintCatalog, "CONSTRAINT_CATALOG", 64, isRequired: true);
        builder.VarcharProperty(e => e.ConstraintSchema, "CONSTRAINT_SCHEMA", 64, isRequired: true);
        builder.VarcharProperty(e => e.ConstraintName, "CONSTRAINT_NAME", 64, isRequired: true);
        builder.VarcharProperty(e => e.UniqueConstraintCatalog, "UNIQUE_CONSTRAINT_CATALOG", 64, isRequired: true);
        builder.VarcharProperty(e => e.UniqueConstraintSchema, "UNIQUE_CONSTRAINT_SCHEMA", 64, isRequired: true);
        builder.VarcharProperty(e => e.UniqueConstraintName, "UNIQUE_CONSTRAINT_NAME", 64, isRequired: false);
        builder.Property(e => e.MatchOption)
            .HasColumnName("MATCH_OPTION")
            .HasColumnType("enum('NONE','PARTIAL','FULL')");
        builder.Property(e => e.UpdateRule)
            .HasColumnName("UPDATE_RULE")
            .HasColumnType("enum('NO ACTION','RESTRICT','CASCADE','SET NULL','SET DEFAULT')");
        builder.Property(e => e.DeleteRule)
            .HasColumnName("DELETE_RULE")
            .HasColumnType("enum('NO ACTION','RESTRICT','CASCADE','SET NULL','SET DEFAULT')");
        builder.VarcharProperty(e => e.TableName, "TABLE_NAME", 64, isRequired: true);
        builder.VarcharProperty(e => e.ReferencedTableName, "REFERENCED_TABLE_NAME", 64, isRequired: true);
    }
}
