// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Entities;

namespace TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Configurations;

public class RoutineConfig : IEntityTypeConfiguration<RoutineEntity>
{
    public void Configure(EntityTypeBuilder<RoutineEntity> builder)
    {
        builder.ToTable("ROUTINES", "information_schema");

        builder.HasKey(e => new { e.RoutineCatalog, e.RoutineSchema, e.RoutineName });

        builder.VarcharProperty(e => e.SpecificName, "SPECIFIC_NAME", 64, isRequired: true);
        builder.VarcharProperty(e => e.RoutineCatalog, "ROUTINE_CATALOG", 64, isRequired: true);
        builder.VarcharProperty(e => e.RoutineSchema, "ROUTINE_SCHEMA", 64, isRequired: true);
        builder.VarcharProperty(e => e.RoutineName, "ROUTINE_NAME", 64, isRequired: true);
        builder.Property(e => e.RoutineType)
            .HasColumnName("ROUTINE_TYPE")
            .HasColumnType("enum('FUNCTION','PROCEDURE')");
        builder.Property(e => e.DataType)
            .HasColumnName("DATA_TYPE")
            .HasColumnType("longtext");
        builder.Property(e => e.CharacterMaximumLength)
            .HasColumnName("CHARACTER_MAXIMUM_LENGTH");
        builder.Property(e => e.CharacterOctetLength)
            .HasColumnName("CHARACTER_OCTET_LENGTH");
        builder.Property(e => e.NumericPrecision)
            .HasColumnName("NUMERIC_PRECISION");
        builder.Property(e => e.NumericScale)
            .HasColumnName("NUMERIC_SCALE");
        builder.Property(e => e.DatetimePrecision)
            .HasColumnName("DATETIME_PRECISION");
        builder.VarcharProperty(e => e.CharacterSetName, "CHARACTER_SET_NAME", 64, isRequired: false);
        builder.VarcharProperty(e => e.CollationName, "COLLATION_NAME", 64, isRequired: false);
        builder.Property(e => e.DtdIdentifier)
            .HasColumnName("DTD_IDENTIFIER")
            .HasColumnType("longtext");
        builder.VarcharProperty(e => e.RoutineBody, "ROUTINE_BODY", 8, isRequired: true);
        builder.Property(e => e.RoutineDefinition)
            .HasColumnName("ROUTINE_DEFINITION")
            .HasColumnType("longtext");
        builder.Property(e => e.ExternalName)
            .HasColumnName("EXTERNAL_NAME")
            .HasColumnType("varbinary(0)");
        builder.VarcharProperty(e => e.ExternalLanguage, "EXTERNAL_LANGUAGE", 64, isRequired: true);
        builder.VarcharProperty(e => e.ParameterStyle, "PARAMETER_STYLE", 3, isRequired: true);
        builder.VarcharProperty(e => e.IsDeterministic, "IS_DETERMINISTIC", 3, isRequired: true);
        builder.Property(e => e.SqlDataAccess)
            .HasColumnName("SQL_DATA_ACCESS")
            .HasColumnType("enum('CONTAINS SQL','NO SQL','READS SQL DATA','MODIFIES SQL DATA')");
        builder.Property(e => e.SqlPath)
            .HasColumnName("SQL_PATH")
            .HasColumnType("varbinary(0)");
        builder.Property(e => e.SecurityType)
            .HasColumnName("SECURITY_TYPE")
            .HasColumnType("enum('DEFAULT','INVOKER','DEFINER')");
        builder.Property(e => e.Created)
            .HasColumnName("CREATED")
            .HasColumnType("timestamp");
        builder.Property(e => e.LastAltered)
            .HasColumnName("LAST_ALTERED")
            .HasColumnType("timestamp");
        builder.Property(e => e.SqlMode)
            .HasColumnName("SQL_MODE")
            .HasColumnType("set('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','NOT_USED','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','NOT_USED_9','NOT_USED_10','NOT_USED_11','NOT_USED_12','NOT_USED_13','NOT_USED_14','NOT_USED_15','NOT_USED_16','NOT_USED_17','NOT_USED_18','ANSI','NO_AUTO_VALUE_ON_ZERO','NO_BACKSLASH_ESCAPES','STRICT_TRANS_TABLES','STRICT_ALL_TABLES','NO_ZERO_IN_DATE','NO_ZERO_DATE','ALLOW_INVALID_DATES','ERROR_FOR_DIVISION_BY_ZERO','TRADITIONAL','NOT_USED_29','HIGH_NOT_PRECEDENCE','NO_ENGINE_SUBSTITUTION','PAD_CHAR_TO_FULL_LENGTH','TIME_TRUNCATE_FRACTIONAL')");
        builder.Property(e => e.RoutineComment)
            .HasColumnName("ROUTINE_COMMENT")
            .HasColumnType("text");
        builder.VarcharProperty(e => e.Definer, "DEFINER", 288, isRequired: true);
        builder.VarcharProperty(e => e.CharacterSetClient, "CHARACTER_SET_CLIENT", 64, isRequired: true);
        builder.VarcharProperty(e => e.CollationConnection, "COLLATION_CONNECTION", 64, isRequired: true);
        builder.VarcharProperty(e => e.DatabaseCollation, "DATABASE_COLLATION", 64, isRequired: true);
    }
}
