// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Entities;

namespace TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Configurations;

public class SchemataConfig : IEntityTypeConfiguration<SchemataEntity>
{
    public void Configure(EntityTypeBuilder<SchemataEntity> builder)
    {
        builder.ToTable("SCHEMATA", "information_schema");

        builder.HasKey(e => new { e.CatalogName, e.SchemaName });

        builder.VarcharProperty(e => e.CatalogName, "CATALOG_NAME", 64, isRequired: true);
        builder.VarcharProperty(e => e.SchemaName, "SCHEMA_NAME", 64, isRequired: true);
        builder.VarcharProperty(e => e.DefaultCharacterSetName, "DEFAULT_CHARACTER_SET_NAME", 64, isRequired: true);
        builder.VarcharProperty(e => e.DefaultCollationName, "DEFAULT_COLLATION_NAME", 64, isRequired: true);
        builder.Property(e => e.SqlPath)
            .HasColumnName("SQL_PATH")
            .HasColumnType("varbinary(0)");
        builder.Property(e => e.DefaultEncryption)
            .HasColumnName("DEFAULT_ENCRYPTION")
            .HasColumnType("enum('NO','YES')");
    }
}
