// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Entities;

namespace TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Configurations;

public class StatisticsConfig : IEntityTypeConfiguration<StatisticsEntity>
{
    public void Configure(EntityTypeBuilder<StatisticsEntity> builder)
    {
        builder.ToTable("STATISTICS", "information_schema");

        builder.HasKey(e => new { e.TableCatalog, e.TableSchema, e.TableName, e.IndexName, e.SeqInIndex });

        builder.VarcharProperty(e => e.TableCatalog, "TABLE_CATALOG", 64, isRequired: true);
        builder.VarcharProperty(e => e.TableSchema, "TABLE_SCHEMA", 64, isRequired: true);
        builder.VarcharProperty(e => e.TableName, "TABLE_NAME", 64, isRequired: true);
        builder.Property(e => e.NonUnique)
            .HasColumnName("NON_UNIQUE");
        builder.VarcharProperty(e => e.IndexSchema, "INDEX_SCHEMA", 64, isRequired: true);
        builder.VarcharProperty(e => e.IndexName, "INDEX_NAME", 64, isRequired: true);
        builder.Property(e => e.SeqInIndex)
            .HasColumnName("SEQ_IN_INDEX");
        builder.VarcharProperty(e => e.ColumnName, "COLUMN_NAME", 64, isRequired: true);
        builder.VarcharProperty(e => e.Collation, "COLLATION", 1, isRequired: false);
        builder.Property(e => e.Cardinality)
            .HasColumnName("CARDINALITY");
        builder.Property(e => e.SubPart)
            .HasColumnName("SUB_PART");
        builder.Property(e => e.Packed)
            .HasColumnName("PACKED")
            .HasColumnType("varbinary(0)");
        builder.VarcharProperty(e => e.Nullable, "NULLABLE", 3, isRequired: true);
        builder.VarcharProperty(e => e.IndexType, "INDEX_TYPE", 11, isRequired: true);
        builder.VarcharProperty(e => e.Comment, "COMMENT", 8, isRequired: true);
        builder.VarcharProperty(e => e.IndexComment, "INDEX_COMMENT", 2048, isRequired: true);
        builder.VarcharProperty(e => e.IsVisible, "IS_VISIBLE", 3, isRequired: true);
        builder.Property(e => e.Expression)
            .HasColumnName("EXPRESSION")
            .HasColumnType("longtext");
    }
}
