// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Entities;

namespace TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Configurations;

public class TableConfig : IEntityTypeConfiguration<TableEntity>
{
    public void Configure(EntityTypeBuilder<TableEntity> builder)
    {
        builder.ToTable("TABLES", "information_schema");

        builder.HasKey(e => new { e.TableCatalog, e.TableSchema, e.TableName });

        builder.VarcharProperty(e => e.TableCatalog, "TABLE_CATALOG", 64, isRequired: true);
        builder.VarcharProperty(e => e.TableSchema, "TABLE_SCHEMA", 64, isRequired: true);
        builder.VarcharProperty(e => e.TableName, "TABLE_NAME", 64, isRequired: true);
        builder.Property(e => e.TableType)
            .HasColumnName("TABLE_TYPE")
            .HasColumnType("enum('BASE TABLE','VIEW','SYSTEM VIEW')");
        builder.VarcharProperty(e => e.Engine, "ENGINE", 64, isRequired: false);
        builder.Property(e => e.Version)
            .HasColumnName("VERSION");
        builder.Property(e => e.RowFormat)
            .HasColumnName("ROW_FORMAT")
            .HasColumnType("enum('Fixed','Dynamic','Compressed','Redundant','Compact','Paged')");
        builder.Property(e => e.TableRows)
            .HasColumnName("TABLE_ROWS");
        builder.Property(e => e.AvgRowLength)
            .HasColumnName("AVG_ROW_LENGTH");
        builder.Property(e => e.DataLength)
            .HasColumnName("DATA_LENGTH");
        builder.Property(e => e.MaxDataLength)
            .HasColumnName("MAX_DATA_LENGTH");
        builder.Property(e => e.IndexLength)
            .HasColumnName("INDEX_LENGTH");
        builder.Property(e => e.DataFree)
            .HasColumnName("DATA_FREE");
        builder.Property(e => e.AutoIncrement)
            .HasColumnName("AUTO_INCREMENT");
        builder.Property(e => e.CreateTime)
            .HasColumnName("CREATE_TIME")
            .HasColumnType("timestamp");
        builder.Property(e => e.UpdateTime)
            .HasColumnName("UPDATE_TIME")
            .HasColumnType("datetime");
        builder.Property(e => e.CheckTime)
            .HasColumnName("CHECK_TIME")
            .HasColumnType("datetime");
        builder.VarcharProperty(e => e.TableCollation, "TABLE_COLLATION", 64, isRequired: false);
        builder.Property(e => e.Checksum)
            .HasColumnName("CHECKSUM");
        builder.VarcharProperty(e => e.CreateOptions, "CREATE_OPTIONS", 256, isRequired: false);
        builder.Property(e => e.TableComment)
            .HasColumnName("TABLE_COMMENT")
            .HasColumnType("text");
    }
}
