// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Entities;

namespace TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Configurations;

public class TriggerConfig : IEntityTypeConfiguration<TriggerEntity>
{
    public void Configure(EntityTypeBuilder<TriggerEntity> builder)
    {
        builder.ToTable("TRIGGERS", "information_schema");

        builder.HasKey(e => new { e.TriggerCatalog, e.TriggerSchema, e.TriggerName });

        builder.VarcharProperty(e => e.TriggerCatalog, "TRIGGER_CATALOG", 64, isRequired: true);
        builder.VarcharProperty(e => e.TriggerSchema, "TRIGGER_SCHEMA", 64, isRequired: true);
        builder.VarcharProperty(e => e.TriggerName, "TRIGGER_NAME", 64, isRequired: true);
        builder.Property(e => e.EventManipulation)
            .HasColumnName("EVENT_MANIPULATION")
            .HasColumnType("enum('INSERT','UPDATE','DELETE')");
        builder.VarcharProperty(e => e.EventObjectCatalog, "EVENT_OBJECT_CATALOG", 64, isRequired: true);
        builder.VarcharProperty(e => e.EventObjectSchema, "EVENT_OBJECT_SCHEMA", 64, isRequired: true);
        builder.VarcharProperty(e => e.EventObjectTable, "EVENT_OBJECT_TABLE", 64, isRequired: true);
        builder.Property(e => e.ActionOrder)
            .HasColumnName("ACTION_ORDER");
        builder.Property(e => e.ActionCondition)
            .HasColumnName("ACTION_CONDITION")
            .HasColumnType("varbinary(0)");
        builder.Property(e => e.ActionStatement)
            .HasColumnName("ACTION_STATEMENT")
            .HasColumnType("longtext");
        builder.VarcharProperty(e => e.ActionOrientation, "ACTION_ORIENTATION", 3, isRequired: true);
        builder.Property(e => e.ActionTiming)
            .HasColumnName("ACTION_TIMING")
            .HasColumnType("enum('BEFORE','AFTER')");
        builder.Property(e => e.ActionReferenceOldTable)
            .HasColumnName("ACTION_REFERENCE_OLD_TABLE")
            .HasColumnType("varbinary(0)");
        builder.Property(e => e.ActionReferenceNewTable)
            .HasColumnName("ACTION_REFERENCE_NEW_TABLE")
            .HasColumnType("varbinary(0)");
        builder.VarcharProperty(e => e.ActionReferenceOldRow, "ACTION_REFERENCE_OLD_ROW", 3, isRequired: true);
        builder.VarcharProperty(e => e.ActionReferenceNewRow, "ACTION_REFERENCE_NEW_ROW", 3, isRequired: true);
        builder.Property(e => e.Created)
            .HasColumnName("CREATED")
            .HasColumnType("timestamp(2)");
        builder.Property(e => e.SqlMode)
            .HasColumnName("SQL_MODE")
            .HasColumnType("set('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','NOT_USED','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','NOT_USED_9','NOT_USED_10','NOT_USED_11','NOT_USED_12','NOT_USED_13','NOT_USED_14','NOT_USED_15','NOT_USED_16','NOT_USED_17','NOT_USED_18','ANSI','NO_AUTO_VALUE_ON_ZERO','NO_BACKSLASH_ESCAPES','STRICT_TRANS_TABLES','STRICT_ALL_TABLES','NO_ZERO_IN_DATE','NO_ZERO_DATE','ALLOW_INVALID_DATES','ERROR_FOR_DIVISION_BY_ZERO','TRADITIONAL','NOT_USED_29','HIGH_NOT_PRECEDENCE','NO_ENGINE_SUBSTITUTION','PAD_CHAR_TO_FULL_LENGTH','TIME_TRUNCATE_FRACTIONAL')");
        builder.VarcharProperty(e => e.Definer, "DEFINER", 288, isRequired: true);
        builder.VarcharProperty(e => e.CharacterSetClient, "CHARACTER_SET_CLIENT", 64, isRequired: true);
        builder.VarcharProperty(e => e.CollationConnection, "COLLATION_CONNECTION", 64, isRequired: true);
        builder.VarcharProperty(e => e.DatabaseCollation, "DATABASE_COLLATION", 64, isRequired: true);
    }
}
