// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Entities;

namespace TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Configurations;

public class ViewConfig : IEntityTypeConfiguration<ViewEntity>
{
    public void Configure(EntityTypeBuilder<ViewEntity> builder)
    {
        builder.ToTable("VIEWS", "information_schema");

        builder.HasKey(e => new { e.TableCatalog, e.TableSchema, e.TableName });

        builder.VarcharProperty(e => e.TableCatalog, "TABLE_CATALOG", 64, isRequired: true);
        builder.VarcharProperty(e => e.TableSchema, "TABLE_SCHEMA", 64, isRequired: true);
        builder.VarcharProperty(e => e.TableName, "TABLE_NAME", 64, isRequired: true);
        builder.Property(e => e.ViewDefinition)
            .HasColumnName("VIEW_DEFINITION")
            .HasColumnType("longtext");
        builder.Property(e => e.CheckOption)
            .HasColumnName("CHECK_OPTION")
            .HasColumnType("enum('NONE','LOCAL','CASCADED')");
        builder.Property(e => e.IsUpdatable)
            .HasColumnName("IS_UPDATABLE")
            .HasColumnType("enum('NO','YES')");
        builder.VarcharProperty(e => e.Definer, "DEFINER", 288, isRequired: true);
        builder.VarcharProperty(e => e.SecurityType, "SECURITY_TYPE", 7, isRequired: true);
        builder.VarcharProperty(e => e.CharacterSetClient, "CHARACTER_SET_CLIENT", 64, isRequired: true);
        builder.VarcharProperty(e => e.CollationConnection, "COLLATION_CONNECTION", 64, isRequired: true);
    }
}
