// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

namespace TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Entities;

public class CharacterSetEntity
{
    public required string CharacterSetName { get; set; }
    public required string DefaultCollateName { get; set; }
    public required string Description { get; set; }
    public required uint Maxlen { get; set; }
}
