// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

namespace TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Entities;

public class CollationCharacterSetApplicabilityEntity
{
    public required string CollationName { get; set; }
    public required string CharacterSetName { get; set; }
}
