// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

namespace TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Entities;

public class ColumnEntity
{
    public required string TableCatalog { get; set; }
    public required string TableSchema { get; set; }
    public required string TableName { get; set; }
    public required string ColumnName { get; set; }
    public required uint OrdinalPosition { get; set; }
    public string? ColumnDefault { get; set; }
    public required string IsNullable { get; set; }
    public string? DataType { get; set; }
    public long? CharacterMaximumLength { get; set; }
    public long? CharacterOctetLength { get; set; }
    public ulong? NumericPrecision { get; set; }
    public ulong? NumericScale { get; set; }
    public uint? DatetimePrecision { get; set; }
    public string? CharacterSetName { get; set; }
    public string? CollationName { get; set; }
    public required string ColumnType { get; set; }
    public required string ColumnKey { get; set; }
    public string? Extra { get; set; }
    public string? Privileges { get; set; }
    public required string ColumnComment { get; set; }
    public required string GenerationExpression { get; set; }
    public uint? SrsId { get; set; }
}
