// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

namespace TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Entities;

public class EngineEntity
{
    public required string Engine { get; set; }
    public required string Support { get; set; }
    public required string Comment { get; set; }
    public string? Transactions { get; set; }
    public string? Xa { get; set; }
    public string? Savepoints { get; set; }
}
