// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

namespace TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Entities;

public class EventEntity
{
    public required string EventCatalog { get; set; }
    public required string EventSchema { get; set; }
    public required string EventName { get; set; }
    public required string Definer { get; set; }
    public required string TimeZone { get; set; }
    public required string EventBody { get; set; }
    public required string EventDefinition { get; set; }
    public required string EventType { get; set; }
    public DateTime? ExecuteAt { get; set; }
    public string? IntervalValue { get; set; }
    public string? IntervalField { get; set; }
    public required string SqlMode { get; set; }
    public DateTime? Starts { get; set; }
    public DateTime? Ends { get; set; }
    public required string Status { get; set; }
    public required string OnCompletion { get; set; }
    public required DateTime Created { get; set; }
    public required DateTime LastAltered { get; set; }
    public DateTime? LastExecuted { get; set; }
    public required string EventComment { get; set; }
    public required uint Originator { get; set; }
    public required string CharacterSetClient { get; set; }
    public required string CollationConnection { get; set; }
    public required string DatabaseCollation { get; set; }
}
