// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

namespace TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Entities;

public class ParameterEntity
{
    public required string SpecificCatalog { get; set; }
    public required string SpecificSchema { get; set; }
    public required string SpecificName { get; set; }
    public required ulong OrdinalPosition { get; set; }
    public string? ParameterMode { get; set; }
    public string? ParameterName { get; set; }
    public string? DataType { get; set; }
    public long? CharacterMaximumLength { get; set; }
    public long? CharacterOctetLength { get; set; }
    public uint? NumericPrecision { get; set; }
    public long? NumericScale { get; set; }
    public uint? DatetimePrecision { get; set; }
    public string? CharacterSetName { get; set; }
    public string? CollationName { get; set; }
    public required string DtdIdentifier { get; set; }
    public required string RoutineType { get; set; }
}
