// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

namespace TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Entities;

public class ReferentialConstraintEntity
{
    public required string ConstraintCatalog { get; set; }
    public required string ConstraintSchema { get; set; }
    public required string ConstraintName { get; set; }
    public required string UniqueConstraintCatalog { get; set; }
    public required string UniqueConstraintSchema { get; set; }
    public string? UniqueConstraintName { get; set; }
    public required string MatchOption { get; set; }
    public required string UpdateRule { get; set; }
    public required string DeleteRule { get; set; }
    public required string TableName { get; set; }
    public required string ReferencedTableName { get; set; }
}
