// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

namespace TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Entities;

public class TableConstraintEntity
{
    public required string ConstraintCatalog { get; set; }
    public required string ConstraintSchema { get; set; }
    public required string ConstraintName { get; set; }
    public required string TableSchema { get; set; }
    public required string TableName { get; set; }
    public required string ConstraintType { get; set; }
    public required string Enforced { get; set; }
}
