// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

namespace TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Entities;

public class TableEntity
{
    public required string TableCatalog { get; set; }
    public required string TableSchema { get; set; }
    public required string TableName { get; set; }
    public required string TableType { get; set; }
    public string? Engine { get; set; }
    public int? Version { get; set; }
    public string? RowFormat { get; set; }
    public ulong? TableRows { get; set; }
    public ulong? AvgRowLength { get; set; }
    public ulong? DataLength { get; set; }
    public ulong? MaxDataLength { get; set; }
    public ulong? IndexLength { get; set; }
    public ulong? DataFree { get; set; }
    public ulong? AutoIncrement { get; set; }
    public required DateTime CreateTime { get; set; }
    public DateTime? UpdateTime { get; set; }
    public DateTime? CheckTime { get; set; }
    public string? TableCollation { get; set; }
    public long? Checksum { get; set; }
    public string? CreateOptions { get; set; }
    public string? TableComment { get; set; }
}
