// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

namespace TcfOss.DatabaseManager.MySql.DatabaseComms.EntityFramework.Entities;

public class ViewEntity
{
    public required string TableCatalog { get; set; }
    public required string TableSchema { get; set; }
    public required string TableName { get; set; }
    public required string ViewDefinition { get; set; }
    public string? CheckOption { get; set; }
    public string? IsUpdatable { get; set; }
    public required string Definer { get; set; }
    public required string SecurityType { get; set; }
    public required string CharacterSetClient { get; set; }
    public required string CollationConnection { get; set; }
}
