// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

namespace TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Entities;

public class CheckConstraintEntity
{
    public required string ConstraintCatalog { get; set; }
    public required string ConstraintSchema { get; set; }
    public required string TableName { get; set; }
    public required string ConstraintName { get; set; }
    public required string Level { get; set; }
    public required string CheckClause { get; set; }
}
