// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

namespace TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Entities;

public class CollationCharacterSetApplicabilityEntity
{
    public required string CollationName { get; set; }
    public required string CharacterSetName { get; set; }
    public required string FullCollationName { get; set; }
    public required long Id { get; set; }
    public required string IsDefault { get; set; }
}
