// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

namespace TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Entities;

public class ColumnEntity
{
    public required string TableCatalog { get; set; }
    public required string TableSchema { get; set; }
    public required string TableName { get; set; }
    public required string ColumnName { get; set; }
    public required ulong OrdinalPosition { get; set; }
    public string? ColumnDefault { get; set; }
    public required string IsNullable { get; set; }
    public required string DataType { get; set; }
    public ulong? CharacterMaximumLength { get; set; }
    public ulong? CharacterOctetLength { get; set; }
    public ulong? NumericPrecision { get; set; }
    public ulong? NumericScale { get; set; }
    public ulong? DatetimePrecision { get; set; }
    public string? CharacterSetName { get; set; }
    public string? CollationName { get; set; }
    public required string ColumnType { get; set; }
    public required string ColumnKey { get; set; }
    public required string Extra { get; set; }
    public required string Privileges { get; set; }
    public required string ColumnComment { get; set; }
    public required string IsGenerated { get; set; }
    public string? GenerationExpression { get; set; }
}
