// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

namespace TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Entities;

public class KeyColumnUsageEntity
{
    public required string ConstraintCatalog { get; set; }
    public required string ConstraintSchema { get; set; }
    public required string ConstraintName { get; set; }
    public required string TableCatalog { get; set; }
    public required string TableSchema { get; set; }
    public required string TableName { get; set; }
    public required string ColumnName { get; set; }
    public required long OrdinalPosition { get; set; }
    public long? PositionInUniqueConstraint { get; set; }
    public string? ReferencedTableSchema { get; set; }
    public string? ReferencedTableName { get; set; }
    public string? ReferencedColumnName { get; set; }
}
