// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

namespace TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Entities;

public class ParameterEntity
{
    public required string SpecificCatalog { get; set; }
    public required string SpecificSchema { get; set; }
    public required string SpecificName { get; set; }
    public required int OrdinalPosition { get; set; }
    public string? ParameterMode { get; set; }
    public string? ParameterName { get; set; }
    public required string DataType { get; set; }
    public int? CharacterMaximumLength { get; set; }
    public int? CharacterOctetLength { get; set; }
    public int? NumericPrecision { get; set; }
    public int? NumericScale { get; set; }
    public ulong? DatetimePrecision { get; set; }
    public string? CharacterSetName { get; set; }
    public string? CollationName { get; set; }
    public required string DtdIdentifier { get; set; }
    public required string RoutineType { get; set; }
}
