// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

namespace TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Entities;

public class RoutineEntity
{
    public required string SpecificName { get; set; }
    public required string RoutineCatalog { get; set; }
    public required string RoutineSchema { get; set; }
    public required string RoutineName { get; set; }
    public required string RoutineType { get; set; }
    public required string DataType { get; set; }
    public int? CharacterMaximumLength { get; set; }
    public int? CharacterOctetLength { get; set; }
    public int? NumericPrecision { get; set; }
    public int? NumericScale { get; set; }
    public ulong? DatetimePrecision { get; set; }
    public string? CharacterSetName { get; set; }
    public string? CollationName { get; set; }
    public string? DtdIdentifier { get; set; }
    public required string RoutineBody { get; set; }
    public string? RoutineDefinition { get; set; }
    public string? ExternalName { get; set; }
    public string? ExternalLanguage { get; set; }
    public required string ParameterStyle { get; set; }
    public required string IsDeterministic { get; set; }
    public required string SqlDataAccess { get; set; }
    public string? SqlPath { get; set; }
    public required string SecurityType { get; set; }
    public required DateTime Created { get; set; }
    public required DateTime LastAltered { get; set; }
    public required string SqlMode { get; set; }
    public required string RoutineComment { get; set; }
    public required string Definer { get; set; }
    public required string CharacterSetClient { get; set; }
    public required string CollationConnection { get; set; }
    public required string DatabaseCollation { get; set; }
}
