// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

namespace TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Entities;

public class SchemataEntity
{
    public required string CatalogName { get; set; }
    public required string SchemaName { get; set; }
    public required string DefaultCharacterSetName { get; set; }
    public required string DefaultCollationName { get; set; }
    public string? SqlPath { get; set; }
    public required string SchemaComment { get; set; }
}
