// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

namespace TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Entities;

public class StatisticsEntity
{
    public required string TableCatalog { get; set; }
    public required string TableSchema { get; set; }
    public required string TableName { get; set; }
    public required long NonUnique { get; set; }
    public required string IndexSchema { get; set; }
    public required string IndexName { get; set; }
    public required uint SeqInIndex { get; set; }
    public required string ColumnName { get; set; }
    public string? Collation { get; set; }
    public long? Cardinality { get; set; }
    public long? SubPart { get; set; }
    public string? Packed { get; set; }
    public required string Nullable { get; set; }
    public required string IndexType { get; set; }
    public required string Comment { get; set; }
    public required string IndexComment { get; set; }
    public required string Ignored { get; set; }
}
