// <auto-generated>See tools under tools/dbman-dev</auto-generated>
#nullable enable

namespace TcfOss.DatabaseManager.MariaDb.DatabaseComms.EntityFramework.Entities;

public class TriggerEntity
{
    public required string TriggerCatalog { get; set; }
    public required string TriggerSchema { get; set; }
    public required string TriggerName { get; set; }
    public required string EventManipulation { get; set; }
    public required string EventObjectCatalog { get; set; }
    public required string EventObjectSchema { get; set; }
    public required string EventObjectTable { get; set; }
    public required long ActionOrder { get; set; }
    public string? ActionCondition { get; set; }
    public required string ActionStatement { get; set; }
    public required string ActionOrientation { get; set; }
    public required string ActionTiming { get; set; }
    public string? ActionReferenceOldTable { get; set; }
    public string? ActionReferenceNewTable { get; set; }
    public required string ActionReferenceOldRow { get; set; }
    public required string ActionReferenceNewRow { get; set; }
    public DateTime? Created { get; set; }
    public required string SqlMode { get; set; }
    public required string Definer { get; set; }
    public required string CharacterSetClient { get; set; }
    public required string CollationConnection { get; set; }
    public required string DatabaseCollation { get; set; }
}
